set -ox

gsutil cp rendered/l01_escape_anomalies.jpg gs://heavy.www.nakilon.pro/stalker_v4/
gsutil cp rendered/l01_escape_artifacts_eng.jpg gs://heavy.www.nakilon.pro/stalker_v5/
gsutil cp rendered/l01_escape_artifacts_rus.jpg gs://heavy.www.nakilon.pro/stalker_v5/
gsutil cp rendered/l01_escape_mutants_eng.jpg gs://heavy.www.nakilon.pro/stalker_v4/
gsutil cp rendered/l01_escape_mutants_rus.jpg gs://heavy.www.nakilon.pro/stalker_v4/
gsutil cp rendered/l01_escape_npcs.jpg gs://heavy.www.nakilon.pro/stalker_v6/
gsutil cp rendered/l02_garbage_anomalies.jpg gs://heavy.www.nakilon.pro/stalker_v1/
gsutil cp rendered/l02_garbage_artifacts_eng.jpg gs://heavy.www.nakilon.pro/stalker_v5/
gsutil cp rendered/l02_garbage_artifacts_rus.jpg gs://heavy.www.nakilon.pro/stalker_v5/
gsutil cp rendered/l02_garbage_mutants_eng.jpg gs://heavy.www.nakilon.pro/stalker_v1/
gsutil cp rendered/l02_garbage_mutants_rus.jpg gs://heavy.www.nakilon.pro/stalker_v1/
gsutil cp rendered/l02_garbage_npcs.jpg gs://heavy.www.nakilon.pro/stalker_v3/
gsutil cp rendered/l03_agroprom_anomalies.jpg gs://heavy.www.nakilon.pro/stalker_v1/
gsutil cp rendered/l03_agroprom_artifacts_eng.jpg gs://heavy.www.nakilon.pro/stalker_v5/
gsutil cp rendered/l03_agroprom_artifacts_rus.jpg gs://heavy.www.nakilon.pro/stalker_v5/
gsutil cp rendered/l03_agroprom_mutants_eng.jpg gs://heavy.www.nakilon.pro/stalker_v1/
gsutil cp rendered/l03_agroprom_mutants_rus.jpg gs://heavy.www.nakilon.pro/stalker_v1/
gsutil cp rendered/l03_agroprom_npcs.jpg gs://heavy.www.nakilon.pro/stalker_v3/
gsutil cp rendered/l03u_agr_underground_anomalies.jpg gs://heavy.www.nakilon.pro/stalker_v1/
gsutil cp rendered/l03u_agr_underground_artifacts_eng.jpg gs://heavy.www.nakilon.pro/stalker_v1/
gsutil cp rendered/l03u_agr_underground_artifacts_rus.jpg gs://heavy.www.nakilon.pro/stalker_v1/
gsutil cp rendered/l03u_agr_underground_mutants_eng.jpg gs://heavy.www.nakilon.pro/stalker_v1/
gsutil cp rendered/l03u_agr_underground_mutants_rus.jpg gs://heavy.www.nakilon.pro/stalker_v1/
gsutil cp rendered/l03u_agr_underground_npcs.jpg gs://heavy.www.nakilon.pro/stalker_v3/
gsutil cp rendered/l04_darkvalley_anomalies.jpg gs://heavy.www.nakilon.pro/stalker_v1/
gsutil cp rendered/l04_darkvalley_artifacts_eng.jpg gs://heavy.www.nakilon.pro/stalker_v1/
gsutil cp rendered/l04_darkvalley_artifacts_rus.jpg gs://heavy.www.nakilon.pro/stalker_v1/
gsutil cp rendered/l04_darkvalley_mutants_eng.jpg gs://heavy.www.nakilon.pro/stalker_v1/
gsutil cp rendered/l04_darkvalley_mutants_rus.jpg gs://heavy.www.nakilon.pro/stalker_v1/
gsutil cp rendered/l04_darkvalley_npcs.jpg gs://heavy.www.nakilon.pro/stalker_v3/
gsutil cp rendered/l04u_labx18_anomalies.jpg gs://heavy.www.nakilon.pro/stalker_v1/
gsutil cp rendered/l04u_labx18_artifacts_eng.jpg gs://heavy.www.nakilon.pro/stalker_v1/
gsutil cp rendered/l04u_labx18_artifacts_rus.jpg gs://heavy.www.nakilon.pro/stalker_v1/
gsutil cp rendered/l04u_labx18_mutants_eng.jpg gs://heavy.www.nakilon.pro/stalker_v1/
gsutil cp rendered/l04u_labx18_mutants_rus.jpg gs://heavy.www.nakilon.pro/stalker_v1/
gsutil cp rendered/l04u_labx18_npcs.jpg gs://heavy.www.nakilon.pro/stalker_v3/
gsutil cp rendered/l05_bar_anomalies.jpg gs://heavy.www.nakilon.pro/stalker_v1/
gsutil cp rendered/l05_bar_artifacts_eng.jpg gs://heavy.www.nakilon.pro/stalker_v1/
gsutil cp rendered/l05_bar_artifacts_rus.jpg gs://heavy.www.nakilon.pro/stalker_v1/
gsutil cp rendered/l05_bar_mutants_eng.jpg gs://heavy.www.nakilon.pro/stalker_v1/
gsutil cp rendered/l05_bar_mutants_rus.jpg gs://heavy.www.nakilon.pro/stalker_v1/
gsutil cp rendered/l05_bar_npcs.jpg gs://heavy.www.nakilon.pro/stalker_v3/
gsutil cp rendered/l06_rostok_anomalies.jpg gs://heavy.www.nakilon.pro/stalker_v1/
gsutil cp rendered/l06_rostok_artifacts_eng.jpg gs://heavy.www.nakilon.pro/stalker_v1/
gsutil cp rendered/l06_rostok_artifacts_rus.jpg gs://heavy.www.nakilon.pro/stalker_v1/
gsutil cp rendered/l06_rostok_mutants_eng.jpg gs://heavy.www.nakilon.pro/stalker_v1/
gsutil cp rendered/l06_rostok_mutants_rus.jpg gs://heavy.www.nakilon.pro/stalker_v1/
gsutil cp rendered/l06_rostok_npcs.jpg gs://heavy.www.nakilon.pro/stalker_v2/
gsutil cp rendered/l07_military_anomalies.jpg gs://heavy.www.nakilon.pro/stalker_v1/
gsutil cp rendered/l07_military_artifacts_eng.jpg gs://heavy.www.nakilon.pro/stalker_v1/
gsutil cp rendered/l07_military_artifacts_rus.jpg gs://heavy.www.nakilon.pro/stalker_v1/
gsutil cp rendered/l07_military_mutants_eng.jpg gs://heavy.www.nakilon.pro/stalker_v1/
gsutil cp rendered/l07_military_mutants_rus.jpg gs://heavy.www.nakilon.pro/stalker_v1/
gsutil cp rendered/l07_military_npcs.jpg gs://heavy.www.nakilon.pro/stalker_v1/
