set -ex

vips jpegsave rendered/l01_escape_anomalies.jpg preview/l01_escape_anomalies.jpg --Q 20
vips jpegsave rendered/l01_escape_artifacts_eng.jpg preview/l01_escape_artifacts_eng.jpg --Q 20
vips jpegsave rendered/l01_escape_artifacts_rus.jpg preview/l01_escape_artifacts_rus.jpg --Q 20
vips jpegsave rendered/l01_escape_mutants_eng.jpg preview/l01_escape_mutants_eng.jpg --Q 20
vips jpegsave rendered/l01_escape_mutants_rus.jpg preview/l01_escape_mutants_rus.jpg --Q 20
vips jpegsave rendered/l01_escape_npcs_eng.jpg preview/l01_escape_npcs_eng.jpg --Q 20
vips jpegsave rendered/l01_escape_npcs_rus.jpg preview/l01_escape_npcs_rus.jpg --Q 20
vips jpegsave rendered/l02_garbage_anomalies.jpg preview/l02_garbage_anomalies.jpg --Q 20
vips jpegsave rendered/l02_garbage_artifacts_eng.jpg preview/l02_garbage_artifacts_eng.jpg --Q 20
vips jpegsave rendered/l02_garbage_artifacts_rus.jpg preview/l02_garbage_artifacts_rus.jpg --Q 20
vips jpegsave rendered/l02_garbage_mutants_eng.jpg preview/l02_garbage_mutants_eng.jpg --Q 20
vips jpegsave rendered/l02_garbage_mutants_rus.jpg preview/l02_garbage_mutants_rus.jpg --Q 20
vips jpegsave rendered/l02_garbage_npcs_eng.jpg preview/l02_garbage_npcs_eng.jpg --Q 20
vips jpegsave rendered/l02_garbage_npcs_rus.jpg preview/l02_garbage_npcs_rus.jpg --Q 20
vips jpegsave rendered/l03_agroprom_anomalies.jpg preview/l03_agroprom_anomalies.jpg --Q 20
vips jpegsave rendered/l03_agroprom_artifacts_eng.jpg preview/l03_agroprom_artifacts_eng.jpg --Q 20
vips jpegsave rendered/l03_agroprom_artifacts_rus.jpg preview/l03_agroprom_artifacts_rus.jpg --Q 20
vips jpegsave rendered/l03_agroprom_mutants_eng.jpg preview/l03_agroprom_mutants_eng.jpg --Q 20
vips jpegsave rendered/l03_agroprom_mutants_rus.jpg preview/l03_agroprom_mutants_rus.jpg --Q 20
vips jpegsave rendered/l03_agroprom_npcs_eng.jpg preview/l03_agroprom_npcs_eng.jpg --Q 20
vips jpegsave rendered/l03_agroprom_npcs_rus.jpg preview/l03_agroprom_npcs_rus.jpg --Q 20
vips jpegsave rendered/l03u_agr_underground_anomalies.jpg preview/l03u_agr_underground_anomalies.jpg --Q 20
vips jpegsave rendered/l03u_agr_underground_artifacts_eng.jpg preview/l03u_agr_underground_artifacts_eng.jpg --Q 20
vips jpegsave rendered/l03u_agr_underground_artifacts_rus.jpg preview/l03u_agr_underground_artifacts_rus.jpg --Q 20
vips jpegsave rendered/l03u_agr_underground_mutants_eng.jpg preview/l03u_agr_underground_mutants_eng.jpg --Q 20
vips jpegsave rendered/l03u_agr_underground_mutants_rus.jpg preview/l03u_agr_underground_mutants_rus.jpg --Q 20
vips jpegsave rendered/l03u_agr_underground_npcs_eng.jpg preview/l03u_agr_underground_npcs_eng.jpg --Q 20
vips jpegsave rendered/l03u_agr_underground_npcs_rus.jpg preview/l03u_agr_underground_npcs_rus.jpg --Q 20
vips jpegsave rendered/l04_darkvalley_anomalies.jpg preview/l04_darkvalley_anomalies.jpg --Q 20
vips jpegsave rendered/l04_darkvalley_artifacts_eng.jpg preview/l04_darkvalley_artifacts_eng.jpg --Q 20
vips jpegsave rendered/l04_darkvalley_artifacts_rus.jpg preview/l04_darkvalley_artifacts_rus.jpg --Q 20
vips jpegsave rendered/l04_darkvalley_mutants_eng.jpg preview/l04_darkvalley_mutants_eng.jpg --Q 20
vips jpegsave rendered/l04_darkvalley_mutants_rus.jpg preview/l04_darkvalley_mutants_rus.jpg --Q 20
vips jpegsave rendered/l04_darkvalley_npcs_eng.jpg preview/l04_darkvalley_npcs_eng.jpg --Q 20
vips jpegsave rendered/l04_darkvalley_npcs_rus.jpg preview/l04_darkvalley_npcs_rus.jpg --Q 20
vips jpegsave rendered/l04u_labx18_anomalies.jpg preview/l04u_labx18_anomalies.jpg --Q 20
vips jpegsave rendered/l04u_labx18_artifacts_eng.jpg preview/l04u_labx18_artifacts_eng.jpg --Q 20
vips jpegsave rendered/l04u_labx18_artifacts_rus.jpg preview/l04u_labx18_artifacts_rus.jpg --Q 20
vips jpegsave rendered/l04u_labx18_mutants_eng.jpg preview/l04u_labx18_mutants_eng.jpg --Q 20
vips jpegsave rendered/l04u_labx18_mutants_rus.jpg preview/l04u_labx18_mutants_rus.jpg --Q 20
vips jpegsave rendered/l04u_labx18_npcs_eng.jpg preview/l04u_labx18_npcs_eng.jpg --Q 20
vips jpegsave rendered/l04u_labx18_npcs_rus.jpg preview/l04u_labx18_npcs_rus.jpg --Q 20
vips jpegsave rendered/l05_bar_anomalies.jpg preview/l05_bar_anomalies.jpg --Q 20
vips jpegsave rendered/l05_bar_artifacts_eng.jpg preview/l05_bar_artifacts_eng.jpg --Q 20
vips jpegsave rendered/l05_bar_artifacts_rus.jpg preview/l05_bar_artifacts_rus.jpg --Q 20
vips jpegsave rendered/l05_bar_mutants_eng.jpg preview/l05_bar_mutants_eng.jpg --Q 20
vips jpegsave rendered/l05_bar_mutants_rus.jpg preview/l05_bar_mutants_rus.jpg --Q 20
vips jpegsave rendered/l05_bar_npcs_eng.jpg preview/l05_bar_npcs_eng.jpg --Q 20
vips jpegsave rendered/l05_bar_npcs_rus.jpg preview/l05_bar_npcs_rus.jpg --Q 20
vips jpegsave rendered/l06_rostok_anomalies.jpg preview/l06_rostok_anomalies.jpg --Q 20
vips jpegsave rendered/l06_rostok_artifacts_eng.jpg preview/l06_rostok_artifacts_eng.jpg --Q 20
vips jpegsave rendered/l06_rostok_artifacts_rus.jpg preview/l06_rostok_artifacts_rus.jpg --Q 20
vips jpegsave rendered/l06_rostok_mutants_eng.jpg preview/l06_rostok_mutants_eng.jpg --Q 20
vips jpegsave rendered/l06_rostok_mutants_rus.jpg preview/l06_rostok_mutants_rus.jpg --Q 20
vips jpegsave rendered/l06_rostok_npcs_eng.jpg preview/l06_rostok_npcs_eng.jpg --Q 20
vips jpegsave rendered/l06_rostok_npcs_rus.jpg preview/l06_rostok_npcs_rus.jpg --Q 20
vips jpegsave rendered/l07_military_anomalies.jpg preview/l07_military_anomalies.jpg --Q 20
vips jpegsave rendered/l07_military_artifacts_eng.jpg preview/l07_military_artifacts_eng.jpg --Q 20
vips jpegsave rendered/l07_military_artifacts_rus.jpg preview/l07_military_artifacts_rus.jpg --Q 20
vips jpegsave rendered/l07_military_mutants_eng.jpg preview/l07_military_mutants_eng.jpg --Q 20
vips jpegsave rendered/l07_military_mutants_rus.jpg preview/l07_military_mutants_rus.jpg --Q 20
vips jpegsave rendered/l07_military_npcs_eng.jpg preview/l07_military_npcs_eng.jpg --Q 20
vips jpegsave rendered/l07_military_npcs_rus.jpg preview/l07_military_npcs_rus.jpg --Q 20
vips jpegsave rendered/l08_yantar_anomalies.jpg preview/l08_yantar_anomalies.jpg --Q 20
vips jpegsave rendered/l08_yantar_artifacts_eng.jpg preview/l08_yantar_artifacts_eng.jpg --Q 20
vips jpegsave rendered/l08_yantar_artifacts_rus.jpg preview/l08_yantar_artifacts_rus.jpg --Q 20
vips jpegsave rendered/l08_yantar_mutants_eng.jpg preview/l08_yantar_mutants_eng.jpg --Q 20
vips jpegsave rendered/l08_yantar_mutants_rus.jpg preview/l08_yantar_mutants_rus.jpg --Q 20
vips jpegsave rendered/l08_yantar_npcs_eng.jpg preview/l08_yantar_npcs_eng.jpg --Q 20
vips jpegsave rendered/l08_yantar_npcs_rus.jpg preview/l08_yantar_npcs_rus.jpg --Q 20
vips jpegsave rendered/l08u_brainlab_anomalies.jpg preview/l08u_brainlab_anomalies.jpg --Q 20
vips jpegsave rendered/l08u_brainlab_artifacts_eng.jpg preview/l08u_brainlab_artifacts_eng.jpg --Q 20
vips jpegsave rendered/l08u_brainlab_artifacts_rus.jpg preview/l08u_brainlab_artifacts_rus.jpg --Q 20
vips jpegsave rendered/l08u_brainlab_mutants_eng.jpg preview/l08u_brainlab_mutants_eng.jpg --Q 20
vips jpegsave rendered/l08u_brainlab_mutants_rus.jpg preview/l08u_brainlab_mutants_rus.jpg --Q 20
vips jpegsave rendered/l08u_brainlab_npcs_eng.jpg preview/l08u_brainlab_npcs_eng.jpg --Q 20
vips jpegsave rendered/l08u_brainlab_npcs_rus.jpg preview/l08u_brainlab_npcs_rus.jpg --Q 20
vips jpegsave rendered/l10_radar_anomalies.jpg preview/l10_radar_anomalies.jpg --Q 20
vips jpegsave rendered/l10_radar_artifacts_eng.jpg preview/l10_radar_artifacts_eng.jpg --Q 20
vips jpegsave rendered/l10_radar_artifacts_rus.jpg preview/l10_radar_artifacts_rus.jpg --Q 20
vips jpegsave rendered/l10_radar_mutants_eng.jpg preview/l10_radar_mutants_eng.jpg --Q 20
vips jpegsave rendered/l10_radar_mutants_rus.jpg preview/l10_radar_mutants_rus.jpg --Q 20
vips jpegsave rendered/l10_radar_npcs_eng.jpg preview/l10_radar_npcs_eng.jpg --Q 20
vips jpegsave rendered/l10_radar_npcs_rus.jpg preview/l10_radar_npcs_rus.jpg --Q 20
vips jpegsave rendered/l10u_bunker_anomalies.jpg preview/l10u_bunker_anomalies.jpg --Q 20
vips jpegsave rendered/l10u_bunker_artifacts_eng.jpg preview/l10u_bunker_artifacts_eng.jpg --Q 20
vips jpegsave rendered/l10u_bunker_artifacts_rus.jpg preview/l10u_bunker_artifacts_rus.jpg --Q 20
vips jpegsave rendered/l10u_bunker_mutants_eng.jpg preview/l10u_bunker_mutants_eng.jpg --Q 20
vips jpegsave rendered/l10u_bunker_mutants_rus.jpg preview/l10u_bunker_mutants_rus.jpg --Q 20
vips jpegsave rendered/l10u_bunker_npcs_eng.jpg preview/l10u_bunker_npcs_eng.jpg --Q 20
vips jpegsave rendered/l10u_bunker_npcs_rus.jpg preview/l10u_bunker_npcs_rus.jpg --Q 20
vips jpegsave rendered/l11_pripyat_anomalies.jpg preview/l11_pripyat_anomalies.jpg --Q 20
vips jpegsave rendered/l11_pripyat_artifacts_eng.jpg preview/l11_pripyat_artifacts_eng.jpg --Q 20
vips jpegsave rendered/l11_pripyat_artifacts_rus.jpg preview/l11_pripyat_artifacts_rus.jpg --Q 20
vips jpegsave rendered/l11_pripyat_mutants_eng.jpg preview/l11_pripyat_mutants_eng.jpg --Q 20
vips jpegsave rendered/l11_pripyat_mutants_rus.jpg preview/l11_pripyat_mutants_rus.jpg --Q 20
vips jpegsave rendered/l11_pripyat_npcs_eng.jpg preview/l11_pripyat_npcs_eng.jpg --Q 20
vips jpegsave rendered/l11_pripyat_npcs_rus.jpg preview/l11_pripyat_npcs_rus.jpg --Q 20
vips jpegsave rendered/l12_stancia_anomalies.jpg preview/l12_stancia_anomalies.jpg --Q 20
vips jpegsave rendered/l12_stancia_artifacts_eng.jpg preview/l12_stancia_artifacts_eng.jpg --Q 20
vips jpegsave rendered/l12_stancia_artifacts_rus.jpg preview/l12_stancia_artifacts_rus.jpg --Q 20
vips jpegsave rendered/l12_stancia_mutants_eng.jpg preview/l12_stancia_mutants_eng.jpg --Q 20
vips jpegsave rendered/l12_stancia_mutants_rus.jpg preview/l12_stancia_mutants_rus.jpg --Q 20
vips jpegsave rendered/l12_stancia_npcs_eng.jpg preview/l12_stancia_npcs_eng.jpg --Q 20
vips jpegsave rendered/l12_stancia_npcs_rus.jpg preview/l12_stancia_npcs_rus.jpg --Q 20
vips jpegsave rendered/l12_stancia_2_anomalies.jpg preview/l12_stancia_2_anomalies.jpg --Q 20
vips jpegsave rendered/l12_stancia_2_artifacts_eng.jpg preview/l12_stancia_2_artifacts_eng.jpg --Q 20
vips jpegsave rendered/l12_stancia_2_artifacts_rus.jpg preview/l12_stancia_2_artifacts_rus.jpg --Q 20
vips jpegsave rendered/l12_stancia_2_mutants_eng.jpg preview/l12_stancia_2_mutants_eng.jpg --Q 20
vips jpegsave rendered/l12_stancia_2_mutants_rus.jpg preview/l12_stancia_2_mutants_rus.jpg --Q 20
vips jpegsave rendered/l12_stancia_2_npcs_eng.jpg preview/l12_stancia_2_npcs_eng.jpg --Q 20
vips jpegsave rendered/l12_stancia_2_npcs_rus.jpg preview/l12_stancia_2_npcs_rus.jpg --Q 20
