set -ox

vips jpegsave rendered/l01_escape_anomalies.jpg preview/l01_escape_anomalies.jpg --Q 20
vips jpegsave rendered/l01_escape_artifacts_eng.jpg preview/l01_escape_artifacts_eng.jpg --Q 20
vips jpegsave rendered/l01_escape_artifacts_rus.jpg preview/l01_escape_artifacts_rus.jpg --Q 20
vips jpegsave rendered/l01_escape_mutants_eng.jpg preview/l01_escape_mutants_eng.jpg --Q 20
vips jpegsave rendered/l01_escape_mutants_rus.jpg preview/l01_escape_mutants_rus.jpg --Q 20
vips jpegsave rendered/l01_escape_npcs.jpg preview/l01_escape_npcs.jpg --Q 20
vips jpegsave rendered/l02_garbage_anomalies.jpg preview/l02_garbage_anomalies.jpg --Q 20
vips jpegsave rendered/l02_garbage_artifacts_eng.jpg preview/l02_garbage_artifacts_eng.jpg --Q 20
vips jpegsave rendered/l02_garbage_artifacts_rus.jpg preview/l02_garbage_artifacts_rus.jpg --Q 20
vips jpegsave rendered/l02_garbage_mutants_eng.jpg preview/l02_garbage_mutants_eng.jpg --Q 20
vips jpegsave rendered/l02_garbage_mutants_rus.jpg preview/l02_garbage_mutants_rus.jpg --Q 20
vips jpegsave rendered/l02_garbage_npcs.jpg preview/l02_garbage_npcs.jpg --Q 20
vips jpegsave rendered/l03_agroprom_anomalies.jpg preview/l03_agroprom_anomalies.jpg --Q 20
vips jpegsave rendered/l03_agroprom_artifacts_eng.jpg preview/l03_agroprom_artifacts_eng.jpg --Q 20
vips jpegsave rendered/l03_agroprom_artifacts_rus.jpg preview/l03_agroprom_artifacts_rus.jpg --Q 20
vips jpegsave rendered/l03_agroprom_mutants_eng.jpg preview/l03_agroprom_mutants_eng.jpg --Q 20
vips jpegsave rendered/l03_agroprom_mutants_rus.jpg preview/l03_agroprom_mutants_rus.jpg --Q 20
vips jpegsave rendered/l03_agroprom_npcs.jpg preview/l03_agroprom_npcs.jpg --Q 20
vips jpegsave rendered/l03u_agr_underground_anomalies.jpg preview/l03u_agr_underground_anomalies.jpg --Q 20
vips jpegsave rendered/l03u_agr_underground_artifacts_eng.jpg preview/l03u_agr_underground_artifacts_eng.jpg --Q 20
vips jpegsave rendered/l03u_agr_underground_artifacts_rus.jpg preview/l03u_agr_underground_artifacts_rus.jpg --Q 20
vips jpegsave rendered/l03u_agr_underground_mutants_eng.jpg preview/l03u_agr_underground_mutants_eng.jpg --Q 20
vips jpegsave rendered/l03u_agr_underground_mutants_rus.jpg preview/l03u_agr_underground_mutants_rus.jpg --Q 20
vips jpegsave rendered/l03u_agr_underground_npcs.jpg preview/l03u_agr_underground_npcs.jpg --Q 20
vips jpegsave rendered/l04_darkvalley_anomalies.jpg preview/l04_darkvalley_anomalies.jpg --Q 20
vips jpegsave rendered/l04_darkvalley_artifacts_eng.jpg preview/l04_darkvalley_artifacts_eng.jpg --Q 20
vips jpegsave rendered/l04_darkvalley_artifacts_rus.jpg preview/l04_darkvalley_artifacts_rus.jpg --Q 20
vips jpegsave rendered/l04_darkvalley_mutants_eng.jpg preview/l04_darkvalley_mutants_eng.jpg --Q 20
vips jpegsave rendered/l04_darkvalley_mutants_rus.jpg preview/l04_darkvalley_mutants_rus.jpg --Q 20
vips jpegsave rendered/l04_darkvalley_npcs.jpg preview/l04_darkvalley_npcs.jpg --Q 20
vips jpegsave rendered/l04u_labx18_anomalies.jpg preview/l04u_labx18_anomalies.jpg --Q 20
vips jpegsave rendered/l04u_labx18_artifacts_eng.jpg preview/l04u_labx18_artifacts_eng.jpg --Q 20
vips jpegsave rendered/l04u_labx18_artifacts_rus.jpg preview/l04u_labx18_artifacts_rus.jpg --Q 20
vips jpegsave rendered/l04u_labx18_mutants_eng.jpg preview/l04u_labx18_mutants_eng.jpg --Q 20
vips jpegsave rendered/l04u_labx18_mutants_rus.jpg preview/l04u_labx18_mutants_rus.jpg --Q 20
vips jpegsave rendered/l04u_labx18_npcs.jpg preview/l04u_labx18_npcs.jpg --Q 20
vips jpegsave rendered/l05_bar_anomalies.jpg preview/l05_bar_anomalies.jpg --Q 20
vips jpegsave rendered/l05_bar_artifacts_eng.jpg preview/l05_bar_artifacts_eng.jpg --Q 20
vips jpegsave rendered/l05_bar_artifacts_rus.jpg preview/l05_bar_artifacts_rus.jpg --Q 20
vips jpegsave rendered/l05_bar_mutants_eng.jpg preview/l05_bar_mutants_eng.jpg --Q 20
vips jpegsave rendered/l05_bar_mutants_rus.jpg preview/l05_bar_mutants_rus.jpg --Q 20
vips jpegsave rendered/l05_bar_npcs.jpg preview/l05_bar_npcs.jpg --Q 20
vips jpegsave rendered/l06_rostok_anomalies.jpg preview/l06_rostok_anomalies.jpg --Q 20
vips jpegsave rendered/l06_rostok_artifacts_eng.jpg preview/l06_rostok_artifacts_eng.jpg --Q 20
vips jpegsave rendered/l06_rostok_artifacts_rus.jpg preview/l06_rostok_artifacts_rus.jpg --Q 20
vips jpegsave rendered/l06_rostok_mutants_eng.jpg preview/l06_rostok_mutants_eng.jpg --Q 20
vips jpegsave rendered/l06_rostok_mutants_rus.jpg preview/l06_rostok_mutants_rus.jpg --Q 20
vips jpegsave rendered/l06_rostok_npcs.jpg preview/l06_rostok_npcs.jpg --Q 20
vips jpegsave rendered/l07_military_anomalies.jpg preview/l07_military_anomalies.jpg --Q 20
vips jpegsave rendered/l07_military_artifacts_eng.jpg preview/l07_military_artifacts_eng.jpg --Q 20
vips jpegsave rendered/l07_military_artifacts_rus.jpg preview/l07_military_artifacts_rus.jpg --Q 20
vips jpegsave rendered/l07_military_mutants_eng.jpg preview/l07_military_mutants_eng.jpg --Q 20
vips jpegsave rendered/l07_military_mutants_rus.jpg preview/l07_military_mutants_rus.jpg --Q 20
vips jpegsave rendered/l07_military_npcs.jpg preview/l07_military_npcs.jpg --Q 20
